# Generated by Django 5.0.1 on 2024-02-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Celular',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone fixo'),
        ),
    ]
