# Generated by Django 5.0.1 on 2024-02-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_rename_celular_cliente_celular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviços',
            name='cliente',
        ),
    ]
