# Generated by Django 5.0.1 on 2024-02-07 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_serviços_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviços',
            name='cliente',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
