# Generated by Django 5.0.1 on 2024-02-10 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_serviços_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviços',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
