# Generated by Django 5.0.1 on 2024-02-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nomeId',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nº id'),
        ),
    ]
