# Generated by Django 5.0.1 on 2024-02-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_cliente_nomeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviços',
            name='nomeId',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nº id'),
        ),
    ]
