# Generated by Django 5.0.1 on 2024-02-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_serviços_nomeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviços',
            old_name='nomeId',
            new_name='nomeID',
        ),
    ]
