# Generated by Django 5.0.1 on 2024-02-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_alter_serviços_nomeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviços',
            name='nomeID',
            field=models.CharField(max_length=500, null=True, verbose_name='Nº ID'),
        ),
    ]
