# Generated by Django 5.0.1 on 2024-02-15 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_alter_serviços_nomeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_serviço',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='areaServico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.area_serviço'),
        ),
    ]
