# Generated by Django 5.0.1 on 2024-02-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0017_area_serviço_area_areaservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviços',
            name='nomeID',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nº ID'),
        ),
    ]
