# Generated by Django 5.0.1 on 2024-02-16 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0020_alter_serviços_nomeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='areaServico',
        ),
        migrations.DeleteModel(
            name='Area_serviço',
        ),
    ]
