# Generated by Django 5.0.1 on 2024-02-16 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0021_remove_area_areaservico_delete_area_serviço'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serviços',
            new_name='Servicos',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='serviço',
            new_name='servico',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='serviços',
            new_name='servicos',
        ),
    ]
