# Generated by Django 5.0.1 on 2024-02-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0022_rename_serviços_servicos_rename_serviço_area_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='nomeID',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nº ID'),
        ),
    ]
