# Generated by Django 5.0.1 on 2024-02-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0023_alter_servicos_nomeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='computador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
