# Generated by Django 5.0.1 on 2024-02-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0024_servicos_computador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='cliente',
        ),
    ]
