# Generated by Django 5.0.1 on 2024-02-16 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0025_remove_servicos_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicos',
            old_name='pc',
            new_name='cliente',
        ),
    ]
